 1.	<b>如何改变promise的状态?   </b>  
      (1)resolve(value): 如果当前是pending就会变为resolved   
      (2)reject(reason): 如果当前是pending就会变为rejected   
      (3)抛出异常: 如果当前是pending就会变为rejected
    
2.	<b>一个promise指定多个成功/失败回调函数, 都会调用吗?   </b>    
      当promise改变为对应状态时都会调用 
      ```
      let p = new Promise((resolve, reject) => {
            throw new Error('Promise状态会被标记为rejected')
        });

        p.then(
            value => {
                console.log('value1', value) 
            },
            reason => {
                console.log('reason1', reason) // reason1 Error: Promise状态会被标记为rejected
            }
        ).then(
            value => {
                console.log('value2', value)//value2 undefined
            },
            reason => {
                console.log('reason2', reason)
            }
        )
      ```

3. <b>改变promise状态 和 指定回调函数 谁先谁后?  </b>   
(1) 都有可能, 正常情况下是先指定回调再改变状态, 但也可以先改状态再指定回调    
   + 常规: 先指定回调函数, 后改变的状态 (then立即执行 此时回调函数的状态还未改变，先保存指定的回调函数)
   ```
   new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(1) // 后改变的状态(同时指定数据), 异步执行回调函数
            }, 1000);
    }).then( // 先指定回调函数, 保存当前指定的回调函数
            value => {},
            reason => {
                console.log('reason', reason)
            }
    )
   ```

   + 先改状态再指定回调  
     ①在执行器中直接调用resolve()/reject()
     ```
      new Promise((resolve, reject) => {
            resolve(1) // 先改变的状态(同时指定数据)
        }).then( // 后指定回调函数, 异步执行回调函数
            value => {
                console.log('value2', value)
            },
            reason => {
                console.log('reason2', reason)
            }
        )
     ```
     ②延迟更长时间才调用then()  
     ```
      const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(1) 
            }, 1000);
        })
        setTimeout(() => {
            p.then(
                value => {
                    console.log('value3', value)
                },
                reason => {
                    console.log('reason3', reason)
                }
            )
        }, 1100);
     ```
  
(2)什么时候才能得到数据?   
①如果先指定的回调, 那当状态发生改变时, 回调函数就会调用, 得到数据  
②如果先改变的状态, 那当指定回调时, 回调函数就会调用, 得到数据    

4.   <b>promise.then()返回的新promise的结果状态由什么决定? </b>  
     1. 简单表达: 由then()指定的回调函数执行的结果决定
     2. 详细表达:    
      ①如果抛出异常, 新promise变为rejected, reason为抛出的异常   
      ②如果返回的是非promise的任意值, 新promise变为resolved, value为返回的值    
      ③如果返回的是另一个新promise, 此promise的结果就会成为新promise的结果       

      输出结果：        
       onResolved1() 1   
       onResolved2() undefined  
       undefined 的原因是第一个then里面没有写返回值，添加return（或者throw） 后会根据return的内容进行输出

      ```
       new Promise((resolve, reject) => {
            resolve(1)
        }).then(
            value => {
                console.log('onResolved1()', value)
                    // return 2
                    // return Promise.resolve(3)
                    // return Promise.reject(4)
                    // throw 5
            },
            reason => {
                console.log('onRejected1()', reason)
                    // return 2
                    // return Promise.resolve(3)
                    // return Promise.reject(4)
                    // throw 5
            }
        ).then(
            value => {
                console.log('onResolved2()', value)
            },
            reason => {
                console.log('onRejected2()', reason)
            }
        )
      ```  
5.  <B>[链式调用](03.js)    </B>   
   需要注意的是，执行失败的回调只能表明上一步的结果是错误的，不代表下一步也会执行失败的回调 
6. <b>promise异常传透</b>   
  (1)当使用promise的then链式调用时, 可以在最后指定失败的回调  
  (2)前面任何操作出了异常, 都会传到最后失败的回调中处理       
  ```
        new Promise((resolve, reject) => {
            reject(1)
        }).then(
            value => {
                console.log('onResolved1()', value)
                return 2
            },
            // 什么都没写就相当于 reason => {throw reason}  向下抛
        ).then(
            value => {
                console.log('onResolved2()', value)
                return 3
            },
            reason => {
                throw reason
            }
        ).then(
            value => {
                console.log('onResolved3()', value)
            },
            reason => Promise.reject(reason)
        ).catch(reason => {
            console.log('onReejected1()', reason)   //onReejected1() 1
        })
  ```
7. 中断promise链  
  (1)当使用promise的then链式调用时, 在中间中断, 不再调用后面的回调函数     
  (2)办法: 在回调函数中返回一个pending状态的promise对象  
   return new Promise(() => {}) 
  ```
      new Promise((resolve, reject) => {
            reject(1)
        }).then(
            value => {
                console.log('onResolved1()', value)
                return 2
            },
        ).catch(reason => {
            console.log('onReejected1()', reason) //onReejected1() 1
            return new Promise(() => {}) 
            // 返回一个pending的promise  中断promise链   下面的then不再执行
        }).then(
            value => {
                console.log('onResolved3()', value)
            },
            reason => {
                console.log('onReejected2()', reason)
            }
        )
  ```   
